create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  summary text,
  description text,
  date timestamptz not null,
  venue_name text,
  venue_address text,
  category text,
  image text,
  price integer not null default 0
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  status text not null default 'Ny',
  event_title text not null,
  event_date timestamptz not null,
  event_location text
);

grant select on table public.events to anon;
grant select, insert on table public.registrations to anon;
grant usage, select on all sequences in schema public to anon;

insert into public.events
  (id, title, summary, description, date, venue_name, venue_address, category, image, price)
values
  (1, 'Lyd mellem husene', 'En intim aften med nye elektroniske navne og visuelle installationer.', 'Oplev tre upcoming artister i et midlertidigt scenerum mellem Godsbanens værksteder. Aftenen kombinerer elektronisk musik, lys og korte artist talks.', '2026-09-12T19:30:00+02:00', 'Godsbanen', 'Skovgaardsgade 3, Aarhus C', 'Koncert', 'https://images.unsplash.com/photo-1562423426-934230877f7a?q=80&w=2525&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 120),
  (2, 'Byen efter mørke', 'En talk om lys, tryghed og de steder, vi deler efter solnedgang.', 'Arkitekter, designere og lokale beboere mødes til en samtale om, hvordan lys og byrumsdesign påvirker vores oplevelse af byen efter mørkets frembrud.', '2026-09-18T17:00:00+02:00', 'Dokk1', 'Hack Kampmanns Plads 2, Aarhus C', 'Talk', 'https://images.unsplash.com/photo-1569660437240-b27b957bf210?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 0),
  (3, 'Tryk din egen plakat', 'Workshop i analogt tryk med former, farver og typografi.', 'En praktisk workshop for begyndere. Du udvikler et enkelt motiv og trykker din egen A3-plakat. Materialer er inkluderet, og du behøver ingen erfaring.', '2026-09-26T10:00:00+02:00', 'Institut for X', 'Skovgaardsgade 3F, Aarhus C', 'Workshop', 'https://picsum.photos/seed/mellemrum-tryk/1200/800', 175),
  (4, 'Langbord og lokale råvarer', 'Fællesspisning med sæsonens grønt og historier fra producenterne.', 'Vi dækker langbord i gårdrummet og serverer en enkel menu baseret på lokale råvarer. Undervejs fortæller producenterne om råvarerne og arbejdet bag.', '2026-10-02T18:00:00+02:00', 'Folkestedet', 'Carl Blochs Gade 28, Aarhus C', 'Fællesskab', 'https://picsum.photos/seed/mellemrum-mad/1200/800', 95),
  (5, 'Nye stemmer på scenen', 'Poetry slam, oplæsning og åbent mikrofonformat for nye skribenter.', 'En scene for korte tekster, spoken word og nye idéer. Aftenen begynder med inviterede oplæsere og slutter med åben mikrofon.', '2026-10-08T19:00:00+02:00', 'Lynfabrikken', 'Vestergade 49B, Aarhus C', 'Scene', 'https://picsum.photos/seed/mellemrum-ord/1200/800', 60),
  (6, 'Tegn byen sammen', 'En rolig søndag med skitsebog, kaffe og fælles byrumsstudier.', 'Vi går en kort rute gennem midtbyen og tegner undervejs. Til sidst samler vi skitserne over kaffe og deler teknikker og observationer.', '2026-10-18T11:00:00+02:00', 'Mølleparken', 'Møllegade 1, Aarhus C', 'Workshop', 'https://images.unsplash.com/photo-1559070169-a3077159ee16?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 40)
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  description = excluded.description,
  date = excluded.date,
  venue_name = excluded.venue_name,
  venue_address = excluded.venue_address,
  category = excluded.category,
  image = excluded.image,
  price = excluded.price;

insert into public.registrations
  (id, name, email, status, event_title, event_date, event_location)
values
  (1, 'Alma Jensen', 'alma@example.com', 'Bekræftet', 'Lyd mellem husene', '2026-09-12T19:30:00+02:00', 'Godsbanen'),
  (2, 'Noah Larsen', 'noah@example.com', 'Ny', 'Tryk din egen plakat', '2026-09-26T10:00:00+02:00', 'Institut for X')
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  status = excluded.status,
  event_title = excluded.event_title,
  event_date = excluded.event_date,
  event_location = excluded.event_location;

select setval(pg_get_serial_sequence('public.events', 'id'), coalesce((select max(id) from public.events), 1));
select setval(pg_get_serial_sequence('public.registrations', 'id'), coalesce((select max(id) from public.registrations), 1));
